### ISSUE TITLE
Why reimplementing Oauth2?

### ISSUE THREAD

**Issue by bond0O7** [Coding-Bunker/unofficial-discord-client#17]
Apparently there is a class that was introduced in Qt 5.8 "QOAuth2AuthorizationCodeFlow", I didn't know Qt has such thing till later.

If it does not fit the purpose, we can implement our own with "QAbstractOAuth2"

https://doc.qt.io/qt-5/qabstractoauth2.html

https://doc.qt.io/qt-5/qoauth2authorizationcodeflow.html

**Comment by guerinoni** [comment]
@bond0O7 
I changed the login method because OAuth2 can't read all of data about user!
But if you want we can add login also with OAuth and traditional user and pw...
