### ISSUE TITLE
[Question] Does it work on Windows 7?

### ISSUE THREAD

**Issue by SaSiNO97** [Coding-Bunker/unofficial-discord-client#24]
Does it work on Windows 7?

**Comment by guerinoni** [comment]
HI @SaSiNO97,
It should, the software is in the early stage and any bits of help is welcome, but Qt is cross-platform, maybe we can integrate automatic release build with CI.

**Comment by UG40A** [comment]
I think the TravisCI will be good...

**Comment by guerinoni** [comment]
@UG40A 
We have GH Actions but we need to add more checks and automation, in this way we can avoid external service...

**Comment by guerinoni** [comment]
@SaSiNO97
Have you any updates?
