### ISSUE TITLE
I have no idea how to use cmake...

### ISSUE THREAD

**Issue by isolatedYeti** [Coding-Bunker/unofficial-discord-client#33]
I'm so sorry for the dumb comment but, I seriously have no idea how to build this app. I do have cmake installed and I tried using it but it says either "nothing to do for "."", or "no makefile found". I used both of the build commands shown in the "build" section of the readme. Please help me build this app!

**Comment by guerinoni** [comment]
OS?

**Comment by isolatedYeti** [comment]
> 
> 
> OS?

Windows 10, I use Git For Windows to use tools etc.

**Comment by isolatedYeti** [comment]
I have the open source version of qt installed, should I download something else? 
![image](https://user-images.githubusercontent.com/69982507/116890053-3c324300-abfb-11eb-95bf-828c584089d5.png)

**Comment by guerinoni** [comment]
The README says 
```
cmake -S . -B build
cmake --build build
```

**Comment by isolatedYeti** [comment]
![image](https://user-images.githubusercontent.com/69982507/116890483-ab0f9c00-abfb-11eb-8128-fb8603d785eb.png)

**Comment by guerinoni** [comment]
Now I don't have any W10 pc, can you try with QtCreator or other IDE like VS?

**Comment by isolatedYeti** [comment]
Same error 
![image](https://user-images.githubusercontent.com/69982507/116891829-2e7dbd00-abfd-11eb-89b1-9d755002b35f.png)

**Comment by guerinoni** [comment]
It seems your CMake doesn't work well from command line, can you try with an IDE and not using terminal?

**Comment by isolatedYeti** [comment]
I'll install visual studio community now, It'll take a long while :)

**Comment by isolatedYeti** [comment]
So, I'm not sure how to use actual commands "cmake -S . -B build" etc in VS, but I did get this error after trying to build the app:
![image](https://user-images.githubusercontent.com/69982507/116896354-2a07d300-ac02-11eb-98a6-77f0aa794b8e.png)

**Comment by guerinoni** [comment]
Qt are free for open source

**Comment by isolatedYeti** [comment]
I got it to work after loooooooooooooots of fiddling and searching stuff up. Thank you for the assistance!

**Comment by guerinoni** [comment]
Thank you to you, I will close this issues, if you think there are more info about windows build that you want put in README pls open a PR :)
