### ISSUE TITLE
Qml vs Qwidgets

### ISSUE THREAD

**Issue by guerinoni** [Coding-Bunker/unofficial-discord-client#5]
Thread to decide how to implement UX
- Qt widgets with CSS or other nice things
- Qt widgets and some item in qml
- Qml only

Any suggestions?

**Comment by bond0O7** [comment]
Qt widgets feel native to the specific platform and are more exposed to the Qt library than Qml(which means easier to develop), on the other case Qml with its fancy look and feel has some performance flows but can also have integration with Qt widgets so it will have some boost
So it's better to combine both for native and fancy look

**Comment by guerinoni** [comment]
QML seems has good support for desktop platform nowadays and Widget are not maintained!
