### ISSUE TITLE
Snowflake type

### ISSUE THREAD

**Issue by bond0O7** [Coding-Bunker/unofficial-discord-client#7]
How do we represent the snowflake type in the code?
here are my proposals:

1. QString Type
2. Reinventing the wheel
3. A 3rd library(not sure if there is)

**Comment by guerinoni** [comment]
We can use QString or qint64/int64_t

**Comment by bond0O7** [comment]
I did some researches, but I couldn't find a resource to confirm its size

**Comment by guerinoni** [comment]
@bond0O7 
Check PR
